// Generated by CoffeeScript 1.9.1
(function() {
  var Experiment, Laboratory, getSeedFromTime;

  Experiment = require("./experiment");

  getSeedFromTime = require('./util').getSeedFromTime;

  Laboratory = (function() {
    function Laboratory(store) {
      this.store = store;
      this.experiments = {};
    }

    Laboratory.prototype.seedFromTime = function(time) {
      var experiment, name, ref, results;
      this.seedFunction = function() {
        return getSeedFromTime(time);
      };
      ref = this.experiments;
      results = [];
      for (name in ref) {
        experiment = ref[name];
        results.push(experiment.seedFunction = this.seedFunction);
      }
      return results;
    };

    Laboratory.prototype.addExperiment = function(name) {
      var experiment;
      experiment = new Experiment(name, this.store);
      if (this.seedFunction) {
        experiment.seedFunction = this.seedFunction;
      }
      this.experiments[name] = experiment;
      return experiment;
    };

    Laboratory.prototype.get = function(name) {
      if (name == null) {
        throw new Error("Invalid Experiment Name");
      }
      return this.experiments[name];
    };

    Laboratory.prototype.run = function(name) {
      var ref;
      return (ref = this.get(name)) != null ? ref.run() : void 0;
    };

    return Laboratory;

  })();

  module.exports = Laboratory;

}).call(this);
