// Generated by CoffeeScript 1.9.1
(function() {
  module.exports = {
    getSeedFromTime: function(time) {
      return (time.getSeconds() + (time.getMinutes() * 60)) / 60 / 60;
    }
  };

}).call(this);
